# Generated by Django 3.0.3 on 2020-02-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='check_out',
        ),
    ]
