# Generated by Django 3.0.3 on 2020-02-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0002_auto_20200224_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='explain',
            field=models.TextField(default='', null=True),
        ),
    ]
