# Generated by Django 3.0.3 on 2020-03-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equip-photo'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
