# Generated by Django 3.0.3 on 2020-03-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='equiptype',
        ),
        migrations.AddField(
            model_name='equip',
            name='equiptype',
            field=models.CharField(choices=[('camcoder', '캠코더'), ('acamcoder', '캠코더/악세서리'), ('camera', '카메라'), ('acamera', '카메라/악세서리'), ('accessory', '악세서리'), ('sound', '음향장비')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equip',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equip',
            name='serial_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Equiptype',
        ),
    ]
