# Generated by Django 3.0.3 on 2020-03-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0007_auto_20200306_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
