# Generated by Django 3.0.4 on 2020-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0008_delete_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equip',
            options={'ordering': ['equiptype', 'name']},
        ),
        migrations.AlterField(
            model_name='equip',
            name='equiptype',
            field=models.CharField(choices=[('3camcoder', '캠코더'), ('4acamcoder', '캠코더/악세서리'), ('1camera', '카메라'), ('2acamera', '카메라/악세서리'), ('5accessory', '악세서리'), ('6sound', '음향장비')], max_length=20, null=True),
        ),
    ]
