# Generated by Django 3.0.4 on 2020-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0009_auto_20200313_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='equiptype',
            field=models.CharField(choices=[('camcoder', '캠코더'), ('camcoder', '캠코더/악세서리'), ('amera', '카메라'), ('acamera', '카메라/악세서리'), ('accessory', '악세서리'), ('sound', '음향장비')], max_length=20, null=True),
        ),
    ]
