# Generated by Django 3.0.4 on 2020-03-13 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0011_auto_20200313_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquiptypeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Equip Type Test',
            },
        ),
        migrations.AlterModelOptions(
            name='equip',
            options={'ordering': ['equiptypetest__name', 'name']},
        ),
        migrations.AddField(
            model_name='equip',
            name='equiptypetest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equiptypetest', to='equips.EquiptypeTest'),
        ),
    ]
