# Generated by Django 3.0.4 on 2020-03-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0012_auto_20200313_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equip',
            options={'ordering': ['equiptypetest__name', 'serial_number']},
        ),
    ]
