# Generated by Django 3.0.4 on 2020-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0015_auto_20200313_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='equiptype',
            field=models.CharField(choices=[('1camcoder', '캠코더'), ('2camcoac', '캠코더/악세서리'), ('3camera', '카메라'), ('4cameraac', '카메라/악세서리'), ('5accessory', '악세서리'), ('6sound', '음향장비'), ('test', '테스트')], default='3camera', max_length=20),
        ),
    ]
