# Generated by Django 3.0.4 on 2020-03-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0016_auto_20200313_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='explain',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
