# Generated by Django 3.0.3 on 2020-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departure',
            field=models.CharField(choices=[('연출부', '연출부'), ('writ', '구성작가부'), ('방송기술부', '방송기술부'), ('entr', '엔터테이너부'), ('webc', '웹컨텐츠부')], max_length=6),
        ),
    ]
