# Generated by Django 3.0.3 on 2020-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200224_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='catagory',
            field=models.CharField(choices=[('info', '정보'), ('school', '교내행사'), ('refine', '교양'), ('reality', '예능'), ('perform', '공연'), ('radio', '라디오'), ('surv', '영상제'), ('personal', '개인')], default='', max_length=10),
        ),
    ]
