# Generated by Django 3.0.4 on 2020-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200301_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out',
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_time',
            field=models.TimeField(null=True),
        ),
    ]
