# Generated by Django 3.0.4 on 2020-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200308_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_in_day',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out_day',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
