# Generated by Django 3.0.4 on 2020-03-08 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200308_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 13, 34, 49, 67677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 13, 34, 49, 67677, tzinfo=utc)),
        ),
    ]
