# Generated by Django 3.0.4 on 2020-03-08 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200308_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 14, 4, 14, 892540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 14, 4, 14, 892540, tzinfo=utc)),
        ),
    ]
