# Generated by Django 3.0.4 on 2020-03-10 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200308_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-check_in']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserv_code',
            field=models.CharField(default='e4ae240e703a49158aa5', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserv_confirm',
            field=models.CharField(default='00000000000000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='catagory',
            field=models.CharField(choices=[('info', '정보'), ('school', '교내행사'), ('refine', '교양'), ('realiy', '예능'), ('perform', '공연'), ('radio', '라디오'), ('surv', '영상제'), ('personal', '개인')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 0, 9, 4, 571269)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 0, 9, 4, 571269)),
        ),
    ]
