# Generated by Django 3.0.4 on 2020-03-10 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20200310_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='instant_boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 0, 54, 13, 231472)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 0, 54, 13, 231472)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_confirm',
            field=models.CharField(default='', max_length=20),
        ),
    ]
