# Generated by Django 3.0.4 on 2020-03-10 04:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0009_auto_20200310_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 4, 24, 18, 125717)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 4, 24, 18, 126213)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_code',
            field=models.CharField(blank=True, default='af4ad94531434488bc70', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_confirm',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
