# Generated by Django 3.0.4 on 2020-03-13 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0009_auto_20200313_1907'),
        ('reservations', '0010_auto_20200310_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 19, 7, 45, 573212)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 19, 7, 45, 573212)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='equipment',
            field=models.ManyToManyField(related_name='equipment', to='equips.Equip'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_code',
            field=models.CharField(blank=True, default='ac8cc44ee0304810a31b', max_length=20),
        ),
    ]
