# Generated by Django 3.0.4 on 2020-03-13 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20200313_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 19, 11, 6, 673855)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 19, 11, 6, 673855)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_code',
            field=models.CharField(blank=True, default='9eff84fc89f24894a7bd', max_length=20),
        ),
    ]
