# Generated by Django 3.0.4 on 2020-03-13 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20200313_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 11, 10, 24, 423788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 11, 10, 24, 423788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_code',
            field=models.CharField(blank=True, default='bc3e77c2f32b40acb41d', max_length=20),
        ),
    ]
