# Generated by Django 3.0.4 on 2020-03-16 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_auto_20200313_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 0, 15, 11, 163733)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 0, 15, 11, 163733)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_code',
            field=models.CharField(blank=True, default='ac25', max_length=4),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_confirm',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
